### ISSUE TITLE
Do not automatically reconnect after calling disconnect

### ISSUE THREAD

**Issue by mloughran** [lukeredpath/libPusher#128]
Currently the client will automatically reconnect, which was probably not the intention.

The test app works around this by deallocating the client, see https://github.com/pusher/pusher-test-iOS/commit/eaa2982c4eaf5dab06380672ec3f8d86e6289e9c

**Comment by jsuder** [comment]
I was just going to ask about the same thing :)

**Comment by lukeredpath** [comment]
@mackuba I have just pushed a fix for this on the `master` branch, which means that the client will no longer auto-reconnect under any circumstances if you explicitly call `disconnect`.

In the meantime, you can work around this without deallocating the client by implementing the following delegate method:

```
- (BOOL)pusher:(PTPusher *)pusher connectionWillAutomaticallyReconnect:(PTPusherConnection *)connection afterDelay:(NSTimeInterval)delay
{
    return NO; // prevent auto-reconnect
}

**Comment by mackuba** [comment]
Great, thanks. I've added a workaround like @mloughran said, deleting and recreating the Pusher object in my connect/disconnect methods instead of creating one in init and keeping it. As I understand, returning false from `pusher:connectionWillAutomaticallyReconnect:afterDelay:` would also prevent reconnecting after network errors, and I still want it to reconnect in those cases.
