### ISSUE TITLE
Update to Use SocketRocket v0.4

### ISSUE THREAD

**Issue by Stunner** [lukeredpath/libPusher#181]
SocketRocket has just recently been updated with a new tag: https://github.com/square/SocketRocket/tree/0.4

**Comment by lukeredpath** [comment]
Thanks, I'll wait to review what has changed first but would be good to move to the new version - good to see some movement on that project at last!

**Comment by hamchapman** [comment]
Some users are reporting that app submissions to the app store are being rejected because of SocketRocket using internal API names, as described here: https://github.com/square/SocketRocket/issues/226

Updating to 0.4 would include the fix for this issue (as shown in this PR https://github.com/square/SocketRocket/pull/252) so if you get a chance to look at this Luke it'd be much appreciated :+1:

**Comment by brandons** [comment]
After updating to SocketRocket 0.4, it looks like there are still selector names matching those of private APIs. Specifically:

``` _closeConnection
 _openConnection```

**Comment by hamchapman** [comment]
@brandons there is a commit in a fork to rename those two names here: https://github.com/kommen/SocketRocket/commit/db8c68134be4850f1ea09c3a5051df579c8de084

Are you using cocoapods? If so, you can reference that fork to get the changes in, or you can make you're own fork while waiting for the fixes to be merged into socketrocket's master branch

**Comment by brandons** [comment]
@hamchapman Yes. We're using this fork in our project now, but it's certainly not ideal.

**Comment by Stunner** [comment]
@brandons Interesting, perhaps you can submit an issue for that feature at the [CocoaPods repo](https://github.com/CocoaPods/CocoaPods/issues)? :smile:

**Comment by Reflejo** [comment]
This was already fixed here: https://github.com/square/SocketRocket/pull/252

**Comment by lukeredpath** [comment]
Closed by #185

**Comment by lukeredpath** [comment]
Please see the new 1.6.1 release
